### ISSUE TITLE
Scene doesn't resize after update 4.0.0

### ISSUE THREAD

**Issue by Marcoral** [goxr3plus/FX-BorderlessScene#17]
It seems that update 4.0.0 really broke up many things :/
Starting from this version, BorderlessController is created via constructor, not by FXMLLoader as it used to be up to that version. Now all the resizeControlls (leftPane, rightPane etc.) are NOT being injected by the loader and have null references. Furthermore, BorderlessController.initialize() method is never invoked. I strongly recommend you to revert project back to version 3.1.0.

It would also fix below issue:
https://github.com/goxr3plus/FX-BorderlessScene/issues/16

**Comment by goxr3plus** [comment]
Hm i did it because i like creating the FXML through constructors so it's more clear.

Oh i think i think i have to create tests so we avoid these thinks on future versions.

Constructor Pattern is more clear and extensible on my opinion.

It's everywhere in XR3Player, so whenever i change the name of the class i don't have to go back to fxml and change it also inside the fxml.

Really it doesn't work for you. Let me see what i did wrong :(

**Comment by goxr3plus** [comment]
Do you want me to add you as a collaborator ( if i haven't already) so you can directly commit on the repository :)?

**Comment by Marcoral** [comment]
Sure, it would be great. Being stuck with non-compilant code makes me unable to sleep ;)
But, going back to the topic - I managed to fix your code. Basically, you forgot to remove anchor pane from FXML file, as you create it in Java code internally. Also BorderlessScene and BorderlessPane must share same controller (both BorderlessScene and BorderlessPane were creating it independently of each other). Take a look at my [latest commit](https://github.com/goxr3plus/FX-BorderlessScene/pull/19).

**Comment by goxr3plus** [comment]
Here you go :) => https://github.com/goxr3plus/FX-BorderlessScene/invitations

**Comment by goxr3plus** [comment]
Now you can directly commit when you accept the invitation . Be careful because you have full access :)

**Comment by goxr3plus** [comment]
I released version 4.2.0 after your merging  :)
